export * from './MyProceduresView';
export * from './MyEnrollmentProcessView';
export * from './MyInscriptionFormView';
export * from './MyThesisProcess';
export * from './MyPostponeEnrollmentProcessView';
export * from './MyPostponeFormView';
export * from './MyReintegrationProcessView';
export * from './MyReintegrationFormView';
export * from './MyInternalTransferProcessView';
